### ISSUE TITLE
[feat] Autenticacao para o frontend

### ISSUE THREAD

**Issue by Lu1z-Gust4v0** [talDoFlemis/brain#52]
# **🚀 Nova Feature**

Adicionar autenticacao e protecao de rotas utilizando next auth

## Criterios de aceitacao 

- [x] Persistencia dos dados 
- [x] Conexao com o backend 
- [x] Login funcional 
- [x] Registro funcional 
- [x] Protecao de rotas

**Comment by talDoFlemis** [comment]
closed by #54
